// Auto-generated by autoresearch train.py
#pragma once

#define MODEL_NAME "autoresearch-4L-1024d"
#define DIM 1024
#define HIDDEN 2816
#define HEADS 16
#define KV_HEADS 4
#define HD 64
#define GQA_RATIO (HEADS/KV_HEADS)
#define Q_DIM (HEADS*HD)
#define KV_DIM (KV_HEADS*HD)
#define SEQ 256
#define NLAYERS 4
#define VOCAB 49152

#define DEFAULT_DATA_PATH "../tinystories_smollm2_data00.bin"
#define CKPT_PATH "ane_autoresearch_ckpt.bin"
