// Auto-generated by autoresearch train.py
#pragma once

#define MODEL_NAME "autoresearch-4L-512d"
#define DIM 512
#define HIDDEN 1408
#define HEADS 8
#define KV_HEADS 2
#define HD 64
#define GQA_RATIO (HEADS/KV_HEADS)
#define Q_DIM (HEADS*HD)
#define KV_DIM (KV_HEADS*HD)
#define SEQ 128
#define NLAYERS 4
#define VOCAB 49152

#define DEFAULT_DATA_PATH "../tinystories_smollm2_data00.bin"
#define CKPT_PATH "ane_autoresearch_ckpt.bin"
