#!/usr/bin/env python3
"""ANE autoresearch: agent-editable training configuration.

Generates model config header, compiles the ANE training binary,
runs training with a time budget, and reports metrics.

The agent should ONLY modify the HYPERPARAMETERS section below.
"""
import subprocess, os, sys, time, re

# ===== AGENT-EDITABLE HYPERPARAMETERS =====

# Architecture
DEPTH = 4           # number of transformer layers
DIM = 1024          # model dimension (embedding size)
HIDDEN = 2816       # FFN hidden dimension (typically 2-4x DIM)
HEADS = 16          # number of query attention heads
KV_HEADS = 4        # number of key/value heads (GQA: HEADS must be divisible by KV_HEADS)
HEAD_DIM = 64       # attention head dimension
SEQ = 256           # sequence length

# Training
LR = 3e-4           # peak learning rate (higher LR causes fp16 activation overflow at long training)
WARMUP_STEPS = 100  # linear warmup steps
ACCUM_STEPS = 10    # gradient accumulation steps (effective batch = ACCUM_STEPS * SEQ tokens)
GRAD_CLIP = 1.0     # gradient norm clipping threshold
WEIGHT_DECAY = 0.1  # AdamW weight decay
ADAM_B1 = 0.9       # Adam beta1
ADAM_B2 = 0.95      # Adam beta2

# Training mode (E38: CPU-only is correct default for all model sizes)
CPU_ONLY = True       # Pure CPU fp32 training (no ANE, no IOSurface overhead)
ANE_MATMUL_ONLY = False  # ANE for linear projections only (viable up to DIM=1536)
LOSS_SCALE = 256.0    # gradient scaling (only relevant for ANE modes)

# LoRA fine-tuning
LORA_ENABLED = False  # enable LoRA (freeze base weights, train adapters only)
LORA_RANK = 8         # LoRA rank (4-16 typical)

# Budget
TIME_BUDGET = 120   # wall-clock seconds for quick experiments

# Data (DO NOT MODIFY)
VOCAB = 49152
DATA_PATH = "../tinystories_smollm2_data00.bin"

# ===== END AGENT-EDITABLE =====


def validate_config():
    """Check hyperparameter constraints."""
    assert HEADS % KV_HEADS == 0, f"HEADS ({HEADS}) must be divisible by KV_HEADS ({KV_HEADS})"
    assert DIM == HEADS * HEAD_DIM, f"DIM ({DIM}) must equal HEADS*HEAD_DIM ({HEADS}*{HEAD_DIM}={HEADS*HEAD_DIM})"
    assert DEPTH > 0 and DIM > 0 and HIDDEN > 0
    q_dim = HEADS * HEAD_DIM
    kv_dim = KV_HEADS * HEAD_DIM
    layer_bytes = (q_dim*DIM + 2*kv_dim*DIM + DIM*q_dim + 2*HIDDEN*DIM + DIM*HIDDEN + 2*DIM) * 4
    total_bytes = DEPTH * layer_bytes * 3 + VOCAB * DIM * 4 * 3  # weights + adam m + adam v
    total_gb = total_bytes / 1e9
    print(f"Config: {DEPTH}L, dim={DIM}, hidden={HIDDEN}, {HEADS}Q/{KV_HEADS}KV, hd={HEAD_DIM}")
    q_dim = HEADS * HEAD_DIM
    kv_dim = KV_HEADS * HEAD_DIM
    wq = q_dim * DIM; wk = kv_dim * DIM; wv = kv_dim * DIM; wo = DIM * q_dim
    w1 = HIDDEN * DIM; w2 = DIM * HIDDEN; w3 = HIDDEN * DIM
    params = DEPTH * (wq+wk+wv+wo+w1+w2+w3+2*DIM) + DIM + VOCAB*DIM
    print(f"Params: {params/1e6:.1f}M, Memory: ~{total_gb:.1f}GB")
    if total_gb > 64:
        print(f"WARNING: Estimated memory {total_gb:.1f}GB may exceed available RAM")


def generate_model_header(path):
    """Write model config as C header file."""
    with open(path, 'w') as f:
        f.write('// Auto-generated by autoresearch train.py\n')
        f.write('#pragma once\n\n')
        f.write(f'#define MODEL_NAME "autoresearch-{DEPTH}L-{DIM}d"\n')
        f.write(f'#define DIM {DIM}\n')
        f.write(f'#define HIDDEN {HIDDEN}\n')
        f.write(f'#define HEADS {HEADS}\n')
        f.write(f'#define KV_HEADS {KV_HEADS}\n')
        f.write(f'#define HD {HEAD_DIM}\n')
        f.write(f'#define GQA_RATIO (HEADS/KV_HEADS)\n')
        f.write(f'#define Q_DIM (HEADS*HD)\n')
        f.write(f'#define KV_DIM (KV_HEADS*HD)\n')
        f.write(f'#define SEQ {SEQ}\n')
        f.write(f'#define NLAYERS {DEPTH}\n')
        f.write(f'#define VOCAB {VOCAB}\n\n')
        f.write(f'#define DEFAULT_DATA_PATH "{DATA_PATH}"\n')
        f.write(f'#define CKPT_PATH "ane_autoresearch_ckpt.bin"\n')


def main():
    validate_config()
    train_dir = os.path.dirname(os.path.abspath(__file__))
    header_path = os.path.join(train_dir, "models", "autoresearch.h")

    # Generate model header
    generate_model_header(header_path)

    # Compile
    print(f"\nCompiling...")
    t0 = time.time()
    subprocess.run(["make", "clean"], cwd=train_dir, capture_output=True)
    result = subprocess.run(
        ["make", "MODEL=autoresearch"],
        cwd=train_dir, capture_output=True, text=True
    )
    compile_time = time.time() - t0
    if result.returncode != 0:
        print(f"COMPILE FAIL:\n{result.stderr}")
        print("\n---")
        print("final_loss:       0.000000")
        sys.exit(1)
    print(f"Compiled in {compile_time:.1f}s")

    # Run training
    cmd = [
        "./train",
        "--scratch",
        "--data", DATA_PATH,
        "--lr", str(LR),
        "--warmup", str(WARMUP_STEPS),
        "--accum", str(ACCUM_STEPS),
        "--clip", str(GRAD_CLIP),
        "--steps", "100000",  # large number; --time will stop it
        "--time", str(TIME_BUDGET),
        "--scale", str(LOSS_SCALE),
    ]
    if CPU_ONLY:
        cmd.append("--cpu-only")
    elif ANE_MATMUL_ONLY:
        cmd.append("--ane-matmul-only")
    if LORA_ENABLED:
        cmd.extend(["--lora", "--lora-rank", str(LORA_RANK)])
    print(f"\nTraining for {TIME_BUDGET}s...")
    print(f"Command: {' '.join(cmd)}\n")

    t0 = time.time()
    result = subprocess.run(
        cmd, cwd=train_dir, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        timeout=TIME_BUDGET * 3  # generous timeout for compile + train
    )
    total_time = time.time() - t0

    output = result.stdout
    # Print training output
    print(output)

    if result.returncode != 0:
        print(f"\nTRAINING FAILED (exit code {result.returncode})")
        print("\n---")
        print("final_loss:       0.000000")
        sys.exit(1)


if __name__ == "__main__":
    main()
